AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  GoogleClientSecret:
    Type: String
    NoEcho: true
  TelegramBotToken:
    Type: String
    NoEcho: true
  GoogleClientId:
    Type: String
  OpenAIApiKey:
    Type: String
    NoEcho: true
  GoogleRedirectUri:
    Type: String
  DenizBotToken:
    Type: String
  DenizBotChatId:
    Type: String

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: staging-users
      BillingMode: PAY_PER_REQUEST  # Or use PROVISIONED if you want to set capacity units
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: 
        Type: REGIONAL
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
  stagingwebhook:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: ./webhook
      Timeout: 900
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      # Role: arn:aws:iam::670138744360:role/service-role/webhook-function-role-j98dymo4
      Environment:
        Variables:
          GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
          DYNAMODB_TABLE: !Ref UsersTable
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          GOOGLE_CLIENT_ID: !Ref GoogleClientId
          OPENAI_API_KEY: !Ref OpenAIApiKey
          GOOGLE_REDIRECT_URI: !Ref GoogleRedirectUri
          DENIZ_BOT_TOKEN: !Ref DenizBotToken
          DENIZ_BOT_CHATID: !Ref DenizBotChatId
          ENVIRONMENT: staging
      Events:
        WebhookEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /staging-webhook
            Method: POST
  WebhookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${stagingwebhook}'
      RetentionInDays: 14
Outputs:
  WebhookApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/staging-webhook"